# Generated by Django 5.1.2 on 2024-10-10 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('denomination', models.CharField(max_length=100)),
                ('is_active', models.SmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=50)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Departament',
            fields=[
                ('departament_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_id', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('is_active', models.SmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=50)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departaments', to='api.company')),
            ],
            options={
                'db_table': 'Departaments',
            },
        ),
    ]
